Use /usr/local/lib instead of /usr/libexec
mgoltzsche/podman-static pull request #16
Opened 2021-08-19 22:39 UTC by PhracturedBlue

As per #15 this will move the files currently in /usr/libexec to be in /usr/local/lib instead to help segregate them from distribution-managed files

It does not modify the docker images, since those are already isolated, but instead just focuses on the tar file generation

2021-08-19 22:53 UTC, mgoltzsche requested changes
@PhracturedBlue Thanks!
Though I'd prefer using the same paths within the tar than within the container images to make sure it works since there are a couple of tests run against the container. Having a different file system layout in the tar than within the container image makes it more likely to break at some point.

Please amend your commit to replace the occurrences of `/usr/libexec` with `/usr/local/lib` also within the Dockerfile.

2021-08-19 23:05 UTC, PhracturedBlue commented
I have updated the Dockerfile and ensured that the tests still pass

BTW, thanks for creating this image.  While I personally have no need for it to be MUSL based, packaging podman, cni, slirp4ns, etc together as a portable release is very convenient to use the latest podman on any OS.

2021-08-19 23:12 UTC, mgoltzsche approved these changes
@PhracturedBlue Thanks!

2021-08-19 23:14 UTC, mgoltzsche requested changes
oh, actually, could you please squash and sign your commits?

2021-08-19 23:53 UTC, PhracturedBlue commented
Done

2021-08-20 00:21 UTC, mgoltzsche approved these changes
Thanks!

2021-08-20 00:38 UTC, merged

2021-08-20 01:01 UTC, mgoltzsche commented
fyi: @PhracturedBlue the commit should have been PGP signed as well. I think the DCO sign off actually really makes sense in conjunction with PGP. Though I know I didn't point that out earlier. This is just to let you know so that you can also PGP sign your commits next time.